
name: Automatic Deploy Production

on:
  push:
    branches: [ master ]
      
jobs:
   build:
     runs-on: self-hosted

     steps:
     - uses: actions/checkout@v2

     - name: run script 
       run: bash /home/edison/pull_and_run.sh
