name: Publish Docker image
on: [push, pull_request]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub environment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: http://edison.dimigo.hs.kr
          environment: Production
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      -
        name: Extract branch name from git ref
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch
      -
        name: Push to Docker Hub (in Pull Request)
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          push: true 
          tags: dimigoin/dimigoin-server:${{ github.head_ref }}
      -
        name: Push to Docker Hub (in Master Push)
        if: ${{
          github.event_name == 'push' &&
          steps.extract_branch.outputs.branch == 'master'
        }}
        uses: docker/build-push-action@v2
        with:
          push: true 
          tags: dimigoin/dimigoin-server:latest
