name: Publish Docker image
on: [push, pull_request]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub environment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: http://edison.dimigo.hs.kr
          environment: Production
          deployment_id: 0
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      - name: Push to Docker Hub (in Pull Request)
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v1
        with:
          push: true 
          tags: dimigoin/dimigoin-server:${{ github.ref }}
      - name: Push to Docker Hub (in Master Push)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v1
        with:
          push: true 
          tags: dimigoin/dimigoin-server:latest
