name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: Production
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: dimigoin
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: dimigoin/dimigoin-server
          tag_with_ref: true
