name: Publish Docker image
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub environment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: http://edison.dimigo.hs.kr
          environment: Production
          deployment_id: 0
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: dimigoin
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: dimigoin/dimigoin-server
          tag_with_ref: true
