name: Pull Docker Image and Run
on:
  workflow_run:
    workflows:
      - Publish Docker image
    types:
      - completed
jobs:
  build:
    name: Pull Docker Image and Run
    runs-on: ubuntu-latest
    steps:
    - name: Pull from Docker Hub and Run Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker pull dimigoin/dimigoin-server:latest
          container_id = $(docker ps -q --filter ancestor=dimigoin/dimigoin-server)
          docker stop $(container_id)
          docker rm $(container_id)
          docker run --name dimigoin-prod -p 5000:5000 dimigoin/dimigoin-server
