name: Pull Docker Image
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Pull Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Pull from Docker Hub
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker pull dimigoin/dimigoin-server:latest
          container_id=$(docker ps -q --filter ancestor=dimigoin/dimigoin-server)
          docker stop $($container_id)
          docker rm $($container_id)
          docker run --name dimigoin-prod -p 5000:5000 dimigoin/dimigoin-server
