name: Test Express Application

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    -
      name: Check out the repo
      uses: actions/checkout@v2
    -
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    -
      name: Install dependencies
      run: yarn install
    -
      name: Run test
      run: yarn test
      env:
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        DIMIAPI_URL: ${{ secrets.DIMIAPI_URL }}
        DIMIAPI_ID: ${{ secrets.DIMIAPI_ID }}
        DIMIAPI_PW: ${{ secrets.DIMIAPI_PW }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        NEIS_API_KEY: ${{ secrets.NEIS_API_KEY }}
